fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

wmc_user:
    resource: "@WMCUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
